#!/bin/bash

sudo apt-get update
python3 -m pip install -r ./QAtesting/requirements.txt
# install google chrome
sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get update
sudo apt-get install -y google-chrome-stable
# no need to install chromedriver cos GitHub-Ubuntu-Latest already provides it
